apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-example-debug
  labels:
    app: webhook-example-debug
webhooks:
  - name: webhook-example-debug.agree.cn
    clientConfig:
      # 修改为masterIP
#      url: "https://10.8.1.90:6444/mutate"
      url: ${URL}
      caBundle: ${CA_BUNDLE}
    admissionReviewVersions: [ "v1beta1" ]
    sideEffects: None
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services"]
    namespaceSelector:
      matchLabels:
        webhook-example-debug: enabled

