apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-example
  labels:
    app: webhook-example
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook-example-crb
  labels:
    app: webhook-example
subjects:
  - kind: ServiceAccount
    name: webhook-example
    namespace: webhook-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-example-cr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-example-cr
  labels:
    app: webhook-example
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/approval
      - certificatesigningrequests/status
    verbs:
      - update
      - create
      - get
      - delete
      - watch
  - apiGroups:
      - certificates.k8s.io
    resourceNames:
      - kubernetes.io/legacy-unknown
    resources:
      - signers
    verbs:
      - approve
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-example
  labels:
    app: webhook-example
spec:
  ports:
    - port: 443
      targetPort: 6444
  selector:
    app: webhook-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-example
  labels:
    app: webhook-example
    webhook-example.github.com/app: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-example
  template:
    metadata:
      labels:
        app: webhook-example
    spec:
      serviceAccount: webhook-example
      containers:
        - name: webhook-example
          image: docker.io/webhook-example:v1.0.0_202207261759
          imagePullPolicy: Always
          args:
            - --namespace=webhook-example
            - --log-v=5


