apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-example
  labels:
    app: webhook-example
webhooks:
  - name: webhook-example.github.com
    clientConfig:
      service:
        name: webhook-example
        namespace: webhook-example
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1UQXdOekF6TWpJd09Gb1hEVE16TVRBd05EQXpNakl3T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlpnCnJGUFcwTkhob090N1dac25idXdZTC9sampTNjM2QnhYS3Z5Ykc4YU4xc1NycTdqMkRZSlMrM1V0ZU5iMWFTMEkKTWZhcXQ3NjY1a1F6M0xqdzV4Q1YrWVVnYVJwRm9Ycm8rZnMweFpMdjlteHBtbDhmRUlqbFFvWFJqM3hHQTFILwpEUTZNQkZIemlOTDFyZGlXNUZKNmdtdThCWVY2WFlsR2N4T0E4SWI3UVl1c1NQbHJ6cDduT2RwVlNncGhvZUd4CmU4cFN4NkphQ2ZCR3VwUlBacXh6R3loVmRyV1IxQ3ZXRlZDU1BlWEdFYk1iSjc4R0xmVVlXTGNXUW1sYWZueTQKUEZCUFB3SFZ3NHVkN3BvcDNKS2FLWHVzMlhRcVpsZk9uMFVZVUZ4bnFSV1NCeEM2YytRTkFjd0lYR01ydUJvTwpmRi85RUFrV3MwbUZzTndMNzdjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHc3c0V3dGdzdPMUFLaFB2ZkwrQ3pwZWJGODVNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRDc4WEl5dmNDWi9NSXBjUG9YbwpMMmFQdnZaelhobVpXMFh0Z2Rjb1hZRGZ2b0gyUWsrYjNyY2lvZVl2OFlaM24vVS9ieHdTMlJhZy9NaE9QRjNlCkNmdWhKa0FBRTNFdVhQNDVNLzlUNUpWWGY2QkdVdmZlQ2o5aVI2bmEvTkFGREJZdEJlODF0aStZbHVET2ZMM1EKSTJDT2dGcTlvMzNJYTJZUk9jOFNKT0NhSlhFOU9NUmlFaGtGRENLUkNsTnMzOGp6UFh4VzM0bitJbmljTVJnNgpaQlpIa1BVc1pQUDF5VnhGalRGTVNIRHY1NlNqRGV0RTI2K1Z0d0lWdERWdWpEWDNrdXVCU3BpU0tBbkxac2hsCmd1MlZVdTVFMEdNQTJZek5ucndEd0N3K0o0ancxTlYwYk44WHBHcEd6VGJzcUxlV2QrM01tYXROSWFHdG9HODcKL0pJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: [ "v1beta1" ]
    sideEffects: None
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments"]
    namespaceSelector:
      matchLabels:
        webhook-example: enabled

