apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-example-sa
  labels:
    app: webhook-example

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-example-cr
  labels:
    app: webhook-example
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook-example-crb
  labels:
    app: webhook-example
subjects:
- kind: ServiceAccount
  name: webhook-example-sa
  namespace: webhook-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-example-cr
