apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-example
  labels:
    app: webhook-example
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook-example-crb
  labels:
    app: webhook-example
subjects:
  - kind: ServiceAccount
    name: webhook-example
    namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-example-cr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-example-cr
  labels:
    app: webhook-example
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"